-- SafeCall schema
--
-- The permanent archive stores ONLY privacy-safe artifacts: redacted
-- transcripts, redacted speaker utterances, PII statistics (counts, never
-- values), AI analysis produced from the redacted text, call metadata and
-- audit records. Raw audio and unredacted transcripts are never written here.
--
-- Access model: the browser never queries these tables. All reads/writes go
-- through the SafeCall API using the service role, which scopes every query to
-- the caller's organization. RLS is enabled with no policies so the anon and
-- authenticated roles are denied by default (defense in depth).

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Organizations & users
-- ---------------------------------------------------------------------------

create table if not exists public.organizations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now()
);

create table if not exists public.users (
  id               uuid primary key references auth.users (id) on delete cascade,
  organization_id  uuid not null references public.organizations (id) on delete cascade,
  email            text not null,
  role             text not null default 'admin' check (role in ('admin', 'analyst', 'viewer')),
  created_at       timestamptz not null default now()
);

create index if not exists users_organization_id_idx on public.users (organization_id);

-- ---------------------------------------------------------------------------
-- Calls (safe archive)
-- ---------------------------------------------------------------------------

create table if not exists public.calls (
  id                          uuid primary key default gen_random_uuid(),
  call_number                 bigint generated by default as identity (start with 1001) unique,
  organization_id             uuid not null references public.organizations (id) on delete cascade,
  created_by                  uuid references auth.users (id) on delete set null,
  original_filename           text not null,
  department                  text not null default 'Customer Support',
  source                      text not null default 'upload' check (source in ('upload', 'sample')),
  status                      text not null default 'UPLOADING'
                                check (status in ('UPLOADING', 'TRANSCRIBING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  failed_stage                text,
  error_message               text,
  policy_preset               text not null
                                check (policy_preset in ('CONTACT_CENTER', 'FINANCIAL', 'HEALTHCARE', 'CUSTOM')),
  pii_policies                text[] not null default '{}',
  analysis_enabled            boolean not null default true,
  detected_language           text,
  duration_seconds            numeric(10, 2),
  speakers_count              integer,
  speech_model_used           text,
  assemblyai_transcript_id    text unique,
  safe_audio_path             text,
  safe_audio_format           text check (safe_audio_format in ('mp3', 'wav')),
  redacted_transcript         text,
  pii_counts                  jsonb not null default '{}'::jsonb,
  pii_total                   integer not null default 0,
  pii_types                   text[] not null default '{}',
  ai_summary                  jsonb,
  sentiment                   text check (sentiment in ('positive', 'neutral', 'negative')),
  topics                      text[] not null default '{}',
  created_at                  timestamptz not null default now(),
  submitted_at                timestamptz,
  transcription_completed_at  timestamptz,
  processed_at                timestamptz,
  original_deleted_at         timestamptz,
  updated_at                  timestamptz not null default now(),
  -- Full-text search over SAFE data only (redacted transcript + AI analysis + metadata).
  search_vector tsvector generated always as (
    setweight(jsonb_to_tsvector('english', coalesce(ai_summary, '{}'::jsonb), '["string"]'), 'A') ||
    setweight(to_tsvector('english', coalesce(redacted_transcript, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(department, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(original_filename, '')), 'D')
  ) stored
);

create index if not exists calls_org_created_idx     on public.calls (organization_id, created_at desc);
create index if not exists calls_org_status_idx      on public.calls (organization_id, status);
create index if not exists calls_status_idx          on public.calls (status);
create index if not exists calls_created_at_idx      on public.calls (created_at desc);
create index if not exists calls_org_department_idx  on public.calls (organization_id, department);
create index if not exists calls_org_sentiment_idx   on public.calls (organization_id, sentiment);
create index if not exists calls_search_idx          on public.calls using gin (search_vector);
create index if not exists calls_pii_types_idx       on public.calls using gin (pii_types);
create index if not exists calls_topics_idx          on public.calls using gin (topics);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists calls_set_updated_at on public.calls;
create trigger calls_set_updated_at
  before update on public.calls
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Speaker-separated REDACTED utterances
-- ---------------------------------------------------------------------------

create table if not exists public.call_utterances (
  id        uuid primary key default gen_random_uuid(),
  call_id   uuid not null references public.calls (id) on delete cascade,
  seq       integer not null,
  speaker   text not null,
  start_ms  integer not null,
  end_ms    integer not null,
  text      text not null,
  unique (call_id, seq)
);

-- ---------------------------------------------------------------------------
-- Audit trail (technical IDs and counts only — never raw PII)
-- ---------------------------------------------------------------------------

create table if not exists public.audit_logs (
  id               bigint generated always as identity primary key,
  organization_id  uuid not null references public.organizations (id) on delete cascade,
  call_id          uuid references public.calls (id) on delete set null,
  event_type       text not null,
  metadata         jsonb not null default '{}'::jsonb,
  actor_id         uuid,
  created_at       timestamptz not null default clock_timestamp()
);

create index if not exists audit_logs_org_created_idx on public.audit_logs (organization_id, created_at desc);
create index if not exists audit_logs_call_idx        on public.audit_logs (call_id, created_at);
create index if not exists audit_logs_event_type_idx  on public.audit_logs (organization_id, event_type);

-- ---------------------------------------------------------------------------
-- Per-organization overrides for the PII policy presets
-- ---------------------------------------------------------------------------

create table if not exists public.pii_policy_settings (
  organization_id  uuid not null references public.organizations (id) on delete cascade,
  preset           text not null check (preset in ('CONTACT_CENTER', 'FINANCIAL', 'HEALTHCARE', 'CUSTOM')),
  policies         text[] not null,
  updated_by       uuid,
  updated_at       timestamptz not null default now(),
  primary key (organization_id, preset)
);

-- ---------------------------------------------------------------------------
-- Functions used by the API (service role only)
-- ---------------------------------------------------------------------------

-- Creates an organization + profile for a Supabase Auth user on first use.
create or replace function public.ensure_user_profile(p_user_id uuid, p_email text, p_org_name text)
returns table (user_id uuid, organization_id uuid, email text, role text, organization_name text)
language plpgsql
set search_path = public
as $$
#variable_conflict use_column
declare
  v_org uuid;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  if not exists (select 1 from public.users u where u.id = p_user_id) then
    insert into public.organizations (name)
      values (coalesce(nullif(trim(p_org_name), ''), 'My Organization'))
      returning id into v_org;
    insert into public.users (id, organization_id, email, role)
      values (p_user_id, v_org, p_email, 'admin');
  end if;

  return query
    select u.id, u.organization_id, u.email, u.role, o.name
    from public.users u
    join public.organizations o on o.id = u.organization_id
    where u.id = p_user_id;
end;
$$;

-- Full-text search across an organization's SAFE archive, with highlighted
-- snippets from the redacted transcript.
create or replace function public.search_calls(
  p_org        uuid,
  p_query      text,
  p_status     text default null,
  p_department text default null,
  p_sentiment  text default null,
  p_pii_type   text default null,
  p_from       timestamptz default null,
  p_to         timestamptz default null,
  p_limit      integer default 25,
  p_offset     integer default 0
)
returns table (
  id                uuid,
  call_number       bigint,
  original_filename text,
  department        text,
  status            text,
  sentiment         text,
  topics            text[],
  pii_total         integer,
  pii_types         text[],
  duration_seconds  numeric,
  created_at        timestamptz,
  processed_at      timestamptz,
  summary           text,
  snippet           text,
  rank              real,
  total_count       bigint
)
language sql
stable
set search_path = public
as $$
  with q as (
    select websearch_to_tsquery('english', p_query) as tsq
  ),
  matched as (
    select c.*, ts_rank_cd(c.search_vector, q.tsq) as rnk, q.tsq as tsq
    from public.calls c, q
    where c.organization_id = p_org
      and c.search_vector @@ q.tsq
      and (p_status is null or c.status = p_status)
      and (p_department is null or c.department = p_department)
      and (p_sentiment is null or c.sentiment = p_sentiment)
      and (p_pii_type is null or c.pii_types @> array[p_pii_type])
      and (p_from is null or c.created_at >= p_from)
      and (p_to is null or c.created_at < p_to)
  )
  select
    m.id, m.call_number, m.original_filename, m.department, m.status, m.sentiment, m.topics,
    m.pii_total, m.pii_types, m.duration_seconds, m.created_at, m.processed_at,
    m.ai_summary ->> 'summary',
    ts_headline('english', coalesce(m.redacted_transcript, ''), m.tsq,
      'StartSel=⟦, StopSel=⟧, MaxFragments=2, MaxWords=22, MinWords=8, FragmentDelimiter=" … "'),
    m.rnk,
    count(*) over ()
  from matched m
  order by m.rnk desc, m.created_at desc
  limit greatest(1, least(p_limit, 100))
  offset greatest(0, p_offset);
$$;

-- ---------------------------------------------------------------------------
-- Row level security & privileges
-- ---------------------------------------------------------------------------

alter table public.organizations       enable row level security;
alter table public.users               enable row level security;
alter table public.calls               enable row level security;
alter table public.call_utterances     enable row level security;
alter table public.audit_logs          enable row level security;
alter table public.pii_policy_settings enable row level security;

revoke all on public.organizations, public.users, public.calls, public.call_utterances,
              public.audit_logs, public.pii_policy_settings
  from anon, authenticated;

grant all on public.organizations, public.users, public.calls, public.call_utterances,
             public.audit_logs, public.pii_policy_settings
  to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.ensure_user_profile(uuid, text, text) from public, anon, authenticated;
grant execute on function public.ensure_user_profile(uuid, text, text) to service_role;

revoke all on function public.search_calls(uuid, text, text, text, text, text, timestamptz, timestamptz, integer, integer)
  from public, anon, authenticated;
grant execute on function public.search_calls(uuid, text, text, text, text, text, timestamptz, timestamptz, integer, integer)
  to service_role;

-- ---------------------------------------------------------------------------
-- Private storage bucket for redacted audio (never public)
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('safe-call-audio', 'safe-call-audio', false, 524288000, array['audio/mpeg', 'audio/wav', 'audio/x-wav'])
on conflict (id) do update set public = false;
